### ISSUE TITLE
Centralized inspection architecture for Inbound traffic

### ISSUE THREAD

**Issue by mbouri** [aws-samples/aws-gateway-load-balancer-code-samples#7]
Hello,
I have 2 questions about the Centralized inspection architecture :
1 - why you configure GLWBE on each VPC instead of using TGW to route traffic to the Inspection VPC ?
2 - how we can use the same archi for inboud traffic, from Internet to spoke VPC ? if I understand well the prinicpe of GWLB, it's not possible to do configure EIP on the the fw appliance and do Destination NAT, so how we can do NAT before accessing the GWLB ? I thought maybe I can use Network LB to handle the EIP and on the target specify the IP address of the private instance (on spoke VPC), but I'm not sure if we can do that ? any idea to have the same archi for outbound and inboud flow ?
Regards

**Comment by Brettles** [comment]
To your first question, you can definitely use Transit Gateway - but some customers don't so either way is a valid pattern. Have a look at https://aws.amazon.com/blogs/networking-and-content-delivery/deployment-models-for-aws-network-firewall/ - it's referring to Network Firewall but the way the endpoints and routing works is the same as Gateway Load Balancer.

For your second question, centralised ingress is a little harder but still possible. I'd suggest contacting an AWS Solutions Architect and going through that in person - mainly because there are so many variations and it would be difficult to run through them here.

**Comment by pmankad96** [comment]
Thanks @Brettles for the answers. @mbouri as @Brettles suggested, it would be a good idea to contact an AWS solution architect and going over the design in person. Also, if I understand, you are talking about Distributed architecture. In case of [centralized architecture](https://github.com/aws-samples/aws-gateway-load-balancer-code-samples/tree/main/aws-cloudformation/centralized_architecture), traffic is routed to TGW. You can refer to the relate blog [here](https://aws.amazon.com/blogs/networking-and-content-delivery/centralized-inspection-architecture-with-aws-gateway-load-balancer-and-aws-transit-gateway/) and CloudFormation templates [here](https://github.com/aws-samples/aws-gateway-load-balancer-code-samples/tree/main/aws-cloudformation/centralized_architecture).

I will go ahead and resolve/close the issue.
